version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: gunicorn passwordman.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/src
    expose:
      - "8000"
    environment:
      - DEBUG=False

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
