# Generated by Django 4.1 on 2022-08-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationpassword_alter_organization_passwords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='shared_users',
            new_name='members',
        ),
    ]
