# Generated by Django 4.1 on 2022-08-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_rename_password_password_passwd_access_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='access',
            table='access',
        ),
    ]
