# Generated by Django 4.1 on 2022-08-11 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0003_alter_access_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
