# Generated by Django 4.1 on 2022-08-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_access_created_at_access_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='passwd',
            new_name='password',
        ),
    ]
