# Generated by Django 4.1 on 2022-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0005_rename_passwd_password_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='strength',
            field=models.IntegerField(default=0, verbose_name='Strength'),
        ),
    ]
